version: '3'
services: 
    users:
      build:
        dockerfile: Dockerfile.dev
        context: ./users
      volumes: 
        - /app/node_modules
        - ./users:/app
      ports:
        - "3001:3001"
      depends_on: 
        - mongodb
      environment:
        - MONGO_DB_URI=mongodb://mongodb/microservices
    
    web:
      build:
        dockerfile: Dockerfile.dev
        context: ./web
      volumes: 
        - /web/node_modules
        - ./web:/app
    
    gateway: 
      restart: always
      build: 
        dockerfile: Dockerfile.dev
        context: ./gateway
      ports: 
        - 4000:80
      depends_on: 
        - web  
        - users

    mongodb:
        image: mongo
        ports:
          - "27017:27017"